version: '3.8'

services:
  task:
    build: 
      context: ./src
    image: ecumene-core:dev
    container_name: ecumene-task
    networks:
      - ecumene
    command: task
    volumes:
      - ${DB_WALLET_FOLDER}:/opt/oracle/network/admin
    env_file:
      - .env
  web:
    build: 
      context: ./src
    image: ecumene-core:dev
    container_name: ecumene-web
    networks:
      - ecumene
    command: web
    volumes:
      - ${DB_WALLET_FOLDER}:/opt/oracle/network/admin
    expose:
      - ${WEB_PORT}
    env_file:
      - .env
    depends_on:
      - task
  nginx:
    build: ./nginx
    image: ecumene-nginx:dev
    container_name: ecumene-nginx
    networks:
      - ecumene
    volumes:
      - ${WEB_CERTS_FOLDER}:/etc/ssl/certs/ecumene
    ports:
      - 80:80
      - 443:443
    depends_on:
      - web

networks:
  ecumene:
    name: ecumene