FROM python:3.8-slim-buster as builder

FROM builder AS python-deps

# Install pipenv
RUN pip install pipenv
RUN apt-get update && apt-get install -y --no-install-recommends gcc build-essential libaio1

# Install python dependencies in /.venv
COPY Pipfile .
RUN PIPENV_VENV_IN_PROJECT=1 pipenv install --deploy

FROM builder AS runtime

COPY --from=python-deps /.venv /.venv
ENV PATH="/.venv/bin:$PATH"

# Install orcale runtime deps
# https://cx-oracle.readthedocs.io/en/latest/user_guide/installation.html
# https://download.oracle.com/otn_software/linux/instantclient/215000/instantclient-basic-linux.x64-21.5.0.0.0dbru.zip
ENV ORA_BASE=/opt/oracle
ENV ORA_HOME=$ORA_BASE/instantclient_21_5

RUN apt-get update && apt-get install -y --no-install-recommends wget unzip libaio1

RUN wget -O oracleinstantclient.zip https://download.oracle.com/otn_software/linux/instantclient/215000/instantclient-basic-linux.x64-21.5.0.0.0dbru.zip
RUN mkdir -p $ORA_BASE
RUN mkdir -p $ORA_HOME/lib
RUN unzip oracleinstantclient.zip -d $ORA_BASE
#RUN export LD_LIBRARY_PATH=$ORA_HOME:$LD_LIBRARY_PATH
#RUN echo $ORA_HOME > /etc/ld.so.conf.d/oracle-instantclient.conf
#RUN ldconfig

WORKDIR /bin/app

COPY . .

ENTRYPOINT ["python", "main.py", "web"]