FROM python:3.8-slim-buster as builder

FROM builder AS python-deps

# Install pipenv
RUN pip install pipenv
RUN apt-get update && apt-get install -y --no-install-recommends gcc build-essential libaio1

# Install python dependencies in /.venv
COPY Pipfile .
RUN PIPENV_VENV_IN_PROJECT=1 pipenv install --deploy

FROM builder AS runtime

COPY --from=python-deps /.venv /.venv
ENV PATH="/.venv/bin:$PATH"

# Install orcale runtime deps
# https://cx-oracle.readthedocs.io/en/latest/user_guide/installation.html
# https://download.oracle.com/otn_software/linux/instantclient/215000/instantclient-basic-linux.x64-21.5.0.0.0dbru.zip
ENV ORACLE_BASE=/opt/oracle
ENV ORACLE_HOME=$ORACLE_BASE/instantclient_21_5

RUN apt-get update && apt-get install -y --no-install-recommends wget unzip libaio1

RUN wget -O oracleinstantclient.zip https://download.oracle.com/otn_software/linux/instantclient/215000/instantclient-basic-linux.x64-21.5.0.0.0dbru.zip
RUN mkdir -p $ORACLE_BASE
RUN unzip oracleinstantclient.zip -d $ORACLE_BASE
RUN echo $ORACLE_HOME > /etc/ld.so.conf.d/oracle-instantclient.conf
RUN ldconfig

RUN useradd --create-home appuser
WORKDIR /home/appuser
USER appuser

COPY . .

ENTRYPOINT ["python", "main.py", "web"]