version: '3.8'

services:
  task:
    image: ${IMAGE_HOST}ecumene-core:${IMAGE_TAG}
    container_name: ecumene-task
    networks:
      - ecumene
    command: task
    volumes:
      - ${DB_WALLET_FOLDER}:/opt/oracle/network/admin
    env_file:
      - .env
  web:
    image: ${IMAGE_HOST}ecumene-core:${IMAGE_TAG}
    container_name: ecumene-web
    networks:
      - ecumene
    command: web
    volumes:
      - ${DB_WALLET_FOLDER}:/opt/oracle/network/admin
    expose:
      - ${WEB_PORT}
    env_file:
      - .env
    depends_on:
      - task
  nginx:
    image: ${IMAGE_HOST}ecumene-nginx:${IMAGE_TAG}
    container_name: ecumene-nginx
    networks:
      - ecumene
    volumes:
      - ${WEB_CERTS_FOLDER}/fullchain.pem:/etc/ssl/certs/ecumene/fullchain.pem
      - ${WEB_CERTS_FOLDER}/privkey.pem:/etc/ssl/certs/ecumene/privkey.pem
    ports:
      - 80:80
      - 443:443
    depends_on:
      - web

networks:
  ecumene:
    name: ecumene